export const SET_GAME_DATA = 'SET_GAME_DATA';
export const SET_IS_INITIAL_GAME_DATA_LOADING = 'SET_IS_INITIAL_GAME_DATA_LOADING';
export const SET_IS_INITIAL_GAME_DATA_LOADING_ERROR = 'SET_IS_INITIAL_GAME_DATA_LOADING_ERROR';
export const SET_CURRENT_STAGE = 'SET_CURRENT_STAGE';
