export const SET_CURRENT_DEFINITIONS = 'SET_CURRENT_DEFINITIONS';
export const ON_SUBMIT_DEFINITION = 'ON_SUBMIT_DEFINITION';
export const SET_IS_DEFINITION_INPUT_FORM_LOADING = 'SET_IS_DEFINITION_INPUT_FORM_LOADING';
export const SET_IS_RECENTLY_ADDED_WORDS_LOADING = 'SET_IS_RECENTLY_ADDED_WORDS_LOADING';
